baseURL = "https://joeyshi.xyz/"
languageCode = "en"
title = "Joey Shi - Software Developer"
publishDir = "public"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[params]
author = "Joey Shi"
description = "Software developer and enjoyer of all things math and Linux (I use Arch btw)."

[Taxonomies]
tag = "tags"

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
